/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.BibliotecaDeJogos;
import classes.JogoDigital;
import classes.JogoFisico;
import javax.swing.JOptionPane;

/**
 *
 * @author Higor
 */
public class CadastrarJogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarJogo.class.getName());

    /**
     * Creates new form CadastrarJogo
     */
    public CadastrarJogo() {
        initComponents();
        btnSalvar.setVisible(false);
        btnDeletar.setVisible(false);
        lblEstoque.setVisible(false);
        txtEstoque.setVisible(false);
        txtNome.setEditable(false);
        txtPreco.setEditable(false);
        jComboBoxPlataforma.setEnabled(false);
        jComboBoxVersao.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jComboBoxPlataforma = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBiblioteca = new javax.swing.JTable();
        jComboBoxVersao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE JOGOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 536, -1));

        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 180, -1, -1));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        btnDeletar.setText("DELETAR");
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 180, -1, -1));

        jLabel2.setText("NOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));

        jLabel3.setText("PREÇO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jLabel4.setText("PLATAFORMA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 127, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 56, 177, -1));

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 90, 106, -1));

        jComboBoxPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "PLAYSTATION", "XBOX" }));
        getContentPane().add(jComboBoxPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        tblBiblioteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "PREÇO", "PLATAFORMA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBiblioteca);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 209, -1, 242));

        jComboBoxVersao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "MIDIA FISICA", "MIDIA DIGITAL" }));
        jComboBoxVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVersaoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxVersao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel5.setText("VERSÃO ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, -1, -1));

        lblEstoque.setText("ESTOQUE");
        getContentPane().add(lblEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 59, -1, -1));
        getContentPane().add(txtEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 71, -1));

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void jComboBoxVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVersaoActionPerformed
        int index = jComboBoxVersao.getSelectedIndex();
        if(index == 1) {
            lblEstoque.setVisible(true);
            txtEstoque.setVisible(true);
        }else{
            lblEstoque.setVisible(false);
            txtEstoque.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxVersaoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnSalvar.setVisible(true);
        btnNovo.setVisible(false);
        txtNome.setEditable(true);
        txtPreco.setEditable(true);
        jComboBoxPlataforma.setEnabled(true);
        jComboBoxVersao.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int indexPlataforma = jComboBoxPlataforma.getSelectedIndex();
        int indexVersao = jComboBoxVersao.getSelectedIndex();
        
        if (txtNome.getText().isBlank() || txtPreco.getText().isBlank()) { // acho que nao esquecir nenhuma validacao
            JOptionPane.showMessageDialog(null,"Preencha Todos Os campos!!");
        }
        else if(indexPlataforma == 0 && indexVersao == 0){
           JOptionPane.showMessageDialog(null,"Escolha uma Plataforma e versao!!"); 
        }
        else if(indexPlataforma == 0){
            JOptionPane.showMessageDialog(null,"Escolha uma Plataforma!!");
        }
        else if(indexVersao == 0){
            JOptionPane.showMessageDialog(null,"Escolha uma Versao!!");
        }
        else if(indexVersao == 1 && txtEstoque.getText().isBlank()){
            JOptionPane.showMessageDialog(null,"Determine a quantidade de estoque!!");
        }else if(indexVersao == 1){
            String Plataforma = (String) jComboBoxPlataforma.getSelectedItem();
            JogoFisico jogoFisico = new JogoFisico(txtNome.getText(),Double.parseDouble(txtPreco.getText()),Plataforma,Integer.parseInt(txtEstoque.getText()));
            BibliotecaDeJogos biblioteca = new BibliotecaDeJogos();
            biblioteca.adicionarJogo(jogoFisico);
            JOptionPane.showMessageDialog(null,"Salvo com Sucesso!!");
            limparCampos();
            biblioteca.atualizarTabela(biblioteca.getJogos(), tblBiblioteca);
        }else if(indexVersao == 2){
            String Plataforma = (String) jComboBoxPlataforma.getSelectedItem();
            JogoDigital jogoDigital = new JogoDigital(txtNome.getText(),Double.parseDouble(txtPreco.getText()),Plataforma);
            BibliotecaDeJogos biblioteca = new BibliotecaDeJogos();
            biblioteca.adicionarJogo(jogoDigital);
            JOptionPane.showMessageDialog(null,"Salvo com Sucesso!!");
            limparCampos();
            biblioteca.atualizarTabela(biblioteca.getJogos(), tblBiblioteca);
            
            //falta mostrar na tabela
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        telaInicial.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new CadastrarJogo().setVisible(true));
    }
    public void limparCampos(){
        txtNome.setText("");
        txtPreco.setText("");
        txtEstoque.setText("");
        btnNovo.setVisible(true);
        btnSalvar.setVisible(false);
        btnDeletar.setVisible(false);
        lblEstoque.setVisible(false);
        txtEstoque.setVisible(false);
        txtNome.setEditable(false);
        txtPreco.setEditable(false);
        jComboBoxPlataforma.setEnabled(false);
        jComboBoxVersao.setEnabled(false);
        
        
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBoxPlataforma;
    private javax.swing.JComboBox<String> jComboBoxVersao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JTable tblBiblioteca;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
